### ISSUE TITLE
@hiddenSubmit

### ISSUE THREAD

**Issue by gaillafr** [PrestaShop/paypal#10]
These lines should be removed:
https://github.com/PrestaShop/paypal/blob/master/views/templates/hook/express_checkout_payment_eu.tpl#L26
https://github.com/PrestaShop/paypal/blob/master/views/templates/hook/integral_evolution_payment_eu.tpl#L27

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
