### ISSUE TITLE
Currency unsupported in PayPal's API

### ISSUE THREAD

**Issue by therampagerado** [PrestaShop/paypal#14]
Hello developers,

Can you find a fix for this issue.

When I try to checkout with BGN (which is not supported currency by the API of PayPal) it returns me the following error:

PayPal response:
TIMESTAMP -> 2015-06-09T12:06:39Z
L_ERRORCODE0 -> 10605
L_SHORTMESSAGE0 -> Transaction refused because of an invalid argument. See additional error messages for details.
L_LONGMESSAGE0 -> Currency is not supported
L_SEVERITYCODE0 -> Error 

Module version - 3.9.0 and every prior version is affected.
PS version - 1.6.0.14

Module settings: standard payments (or every other setting is afected)
Module settings in Payments: customer currency (if I select any other currency the module doesn't convert to the proper amount).

Can we have a settings in module page to choose to which currecy to convert prior payment if the current one is not supported?

Regards!

**Comment by therampagerado** [comment]
Could at least I get some responce on this one?

**Comment by tropicodesoftware** [comment]
Hi, I have the same problem. Was this resolved?

**Comment by therampagerado** [comment]
No

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
