### ISSUE TITLE
Uncaught exception 'PrestaShopException' with message 'Property Cart->id_currency is empty'

### ISSUE THREAD

**Issue by simondaigre** [PrestaShop/paypal#18]
Hi,

Got this issue with a PS 1.6.0.13 with a custom 1.5 theme.

In initParameters() function I found this line:

$currency_module = $this->getCurrency((int)$this->context->cart->id_currency);

But there isnt a getCurrency function in your module so it returns a null value.

**Comment by f31n** [comment]
Same here,
i'm using multi shop, with one shop it is working with another one not?

[Wed Feb 24 10:14:08.630740 2016] [:error] [pid 15479] [client 80.108.87.69:50230] PHP Fatal error:  Uncaught exception 'PrestaShopException' with message 'Property Cart->id_currency is empty' in /var/www/html/classes/ObjectModel.php:837\nStack trace:\n#0 /var/www/html/classes/ObjectModel.php(255): ObjectModelCore->validateFields()\n#1 /var/www/html/classes/ObjectModel.php(596): ObjectModelCore->getFields()\n#2 /var/www/html/classes/Cart.php(199): ObjectModelCore->update()\n#3 /var/www/html/modules/paypal/express_checkout/process.php(126): CartCore->update()\n#4 /var/www/html/modules/paypal/express_checkout/process.php(141): PaypalExpressCheckout->initParameters(true)\n#5 /var/www/html/modules/paypal/express_checkout/payment.php(149): PaypalExpressCheckout->setExpressCheckout(false)\n#6 {main}\n  thrown in /var/www/html/classes/ObjectModel.php on line 837, referer: http://URL/quick-order

**Comment by f31n** [comment]
Resolved, it's not a bug from paypal module its a bug from prestashop -> you need to go to payment addons and there you can select which currency to use for each module you installed.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
