### ISSUE TITLE
PHP Notice:  Undefined index: RedirectRequired...

### ISSUE THREAD

**Issue by monpoulet** [PrestaShop/paypal#21]
Hello,

here is a reccurrent PHP Notice that come back on PHP Error Log:
[16-Jul-2015 17:59:31 Europe/Paris] PHP Notice:  Undefined index: RedirectRequired in /home/www/modules/paypal/express_checkout/payment.php on line 317

Apparently an "isset" on the variable result['RedirectRequired'] is missing.
Can you fix it, or tell us how to fix this issue ?
PS 1.6.0.14.

**Comment by drzraf** [comment]
Same using express checkout and 1.6.1.1

**Comment by drzraf** [comment]
see also PR #36
ping upstream

**Comment by DhanashriJoshi** [comment]
Hello, I am trying to use PrestaShop Gem, but when I am trying to update the Product, I am getting following error. Can You Please Give me solution.

:message => "[PHP Notice #8] Undefined index: id (/home/29468-81260.cloudwaysapps.com/nfmgdxmjnm/public_html/classes/Product.php, line 5147)"

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
