### ISSUE TITLE
undefined index PayPal_in_context_checkout (checkout's first step)

### ISSUE THREAD

**Issue by drzraf** [PrestaShop/paypal#24]
Patch:

```
diff --git a/paypal.php b/paypal.php
index 7e6bf3d..3ba166b 100644
--- a/paypal.php
+++ b/paypal.php
@@ -638,6 +638,7 @@ public function hookShoppingCartExtra()
                        'PayPal_lang_code' => (isset($values[$this->context->language->iso_code]) ? $values[$this->context->language->iso_code] : 'en_US'),
                        'PayPal_tracking_code' => $this->getTrackingCode((int)Configuration::get('PAYPAL_PAYMENT_METHOD')),
                        'include_form' => true,
+                       'PayPal_in_context_checkout' => false,
                        'template_dir' => dirname(__FILE__).'/views/templates/hook/'));

                return $this->fetchTemplate('express_checkout_shortcut_button.tpl');
```

**Comment by drzraf** [comment]
ping?

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
