### ISSUE TITLE
no translation for two records on cart

### ISSUE THREAD

**Issue by kullii** [PrestaShop/paypal#3]
When you have finished shopping cart
there ar two entrys in english and there is no translation in module file de.php and in translations of prestashop for german entry
"total of the transaction (tax incl.)"
and
"Your PayPal transaction ID is:"
Bug in Presta?
You can see german-forum-discuss at https://www.prestashop.com/forums/topic/434536-wo-finde-ich-diese-%C3%BCbersetzungen/

thanks

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. For any questions, please contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) or create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
