### ISSUE TITLE
Error.tpl can not override

### ISSUE THREAD

**Issue by nahuelsgk** [PrestaShop/paypal#30]
We are trying to override in our theme but is imposible. I guess the issue is in 
return $this->fetchTemplate('error.tpl');

**Comment by 84pixels** [comment]
Up

**Comment by Colir** [comment]
Hi @nahuelsgk did you find a way to do this override ?

thank you

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
