### ISSUE TITLE
Payment received, Order not created

### ISSUE THREAD

**Issue by jigarius** [PrestaShop/paypal#32]
Hello. I installed the PayPal module on a store I built for a friend (from Malaysia). All is done, but when I checkout using Website Payments Standard, PayPal charges the sum on my Credit Card, but the items remain in cart - no order is created! So basically, the entire checkout fails.

**Comment by PifyZ** [comment]
Same problem here (from France).

PrestaShop v1.5.4.1
PayPal module v3.8.4

(the problem does not happen often, it only happened twice in 1 800 orders)

**Comment by garyconstable** [comment]
I think I have the same issue as this: 
pay pal - returns to this URL, but there is no order ID:
module/paypal/submit?id_cart=16207&id_module=107&id_order=0&key=00a53426a17028d4125dd8a758a6490b

so  $paypal_order = PayPalOrder::getOrderById($this->id_order); will fail?

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
