### ISSUE TITLE
SILOVER error message

### ISSUE THREAD

**Issue by dedisoft** [PrestaShop/paypal#33]
Hi,

We are using PayPal for a while, and Curl has been installed and enabled some times ago.

Since 2 days, we have this error by mail with version 3.10.2 (latest): 

PayPal response:
SILOVER -> name=LIVE6.APIT.1&silo_version=880&app=appdispatcher_apit&TIME=3581240662; domain
TIMESTAMP -> 2015-12-07T12:04:37Z

As Curl is already enabled, we didn't have any other solution.

Have you any suggestion on how to correct this ?

Regards

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
