### ISSUE TITLE
Paypal charge is different than total order

### ISSUE THREAD

**Issue by flav1972** [PrestaShop/paypal#39]
There is a little difference (some cents) between amount charged and the order amount.

Several users have seen this difference. (My version is PS 1.6.1.4 / paypal 3.10.2): see thread on forum: https://www.prestashop.com/forums/topic/461977-paypal-charges-different-amount-than-the-order-value/?hl=%2Bpaypal+%2Bdifference#entry2138298

**Comment by brrrrrrrt** [comment]
same here:

Order Status is set to "Error with Payment".

the money will be sent but because of the order status, the customers think it is not payed and try to buy again with the same result, money being sent but "Error with payment". this is a really bad situation.

![bildschirmfoto von 2016-11-07 16-57-02](https://cloud.githubusercontent.com/assets/4489013/20064494/42ab7630-a50b-11e6-8e03-cab6cb50d9d2.png)

![bildschirmfoto von 2016-11-07 16-50-08](https://cloud.githubusercontent.com/assets/4489013/20064333/9cdaa60e-a50a-11e6-8c41-4f6ba72c572e.png)

![bildschirmfoto von 2016-11-07 16-57-50](https://cloud.githubusercontent.com/assets/4489013/20064686/d55620e8-a50b-11e6-8541-0e49e4e910ca.png)

**Comment by asmadr** [comment]
@brrrrrrrt  I have the same probleme. have your found a solution please ?

**Comment by brrrrrrrt** [comment]
sorry, no real solution, but what i have tried for now is to change the rounding option within "Preferences -> General" from "round on the total" to "round on each item" - it seems the paypal module does not respect this setting and is always rounding on each line or item.

**Comment by asmadr** [comment]
@brrrrrrrt  Thank you, i fixed  with option round on each product.

**Comment by f31n** [comment]
+1

**Comment by SeyitDuman** [comment]
+1

**Comment by ballashop** [comment]
Any news?
I contacted PayPal technical support for more information.

**Comment by kanecko** [comment]
I think 202-ecommerce are the partners that actually develop the PayPal module.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. For any questions, please contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) or create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) or create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
