### ISSUE TITLE
Paypal log always enabled

### ISSUE THREAD

**Issue by flav1972** [PrestaShop/paypal#40]
paypal api log is enabled in version 3.10.2: this causes security issue. The log file is not protected.

The correction is:

```
--- a/paypal/api/paypal_lib.php
+++ b/paypal/api/paypal_lib.php
@@ -31,7 +31,7 @@ define('PAYPAL_API_VERSION', '106.0');
 class PaypalLib
 {

-       private $enable_log = true;
+       private $enable_log = false;
        private $_logs = array();
        protected $paypal = null;
        public function __construct()
```

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
