### ISSUE TITLE
Configuration page of module is completely missformated

### ISSUE THREAD

**Issue by djbuch** [PrestaShop/paypal#42]
On the last PrestaShop version 1.6.1.4 the configuration page in backoffice  is completely missformated as if Javascript was disabled.

Has someone an idea ?

Regards,

**Comment by tucoinfo** [comment]
I don't have a JS issue but the page is indeed nicely broken in 3.10.10 and 3.11.1 "Official Europe" versions. Also 3.11.1 has an express checkout init bug due to a (crazy?) change of an include path.

I always wonder who manages anything here in the repo and what the relationship is to the "Official" version developer on the PS Addons store, if any.

**Comment by tucoinfo** [comment]
Actually it seems crazier than that. If you disable the module then try Configure do you see the correctly formatted page? (even if it is the old config page, without the new options)

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
