### ISSUE TITLE
AuthenticatePaymentMethods.php in 3.10.6

### ISSUE THREAD

**Issue by avdudin** [PrestaShop/paypal#44]
classes/AuthenticatePaymentMethods.php in getPaymentMethodsByIsoCode:
'CZ' => array()
'GB' is completely missing.

Not possible to configure the module - returns 'Your country is not available for this module please go on Prestashop addons to see the different possibilities.' due to this.

**Comment by stevro** [comment]
Any fixes for this? I've installed v3.10.8 and if I choose as a Default Country from Localization module United Kingdom, it says "Your country is not available for this module please go on Prestashop addons to see the different possibilities."

If I choose France for example it works to integrate Paypal.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
