### ISSUE TITLE
Logos not displayed correctly in left column

### ISSUE THREAD

**Issue by Nolaan** [PrestaShop/paypal#52]
When you hook the paypal module to the left column the logo image cannot be found. The path is incorrect. This is due to an inconsistency between the paths in logos.xml and the code. The result path generated is : /modules/paypal/modules/paypal/views... Either you remove the constant _PS_MODULE_DIR or the prefix "/modules/paypal" in logos.xml in the tag LocalPayPalVerticalSolutionPP.

Note : some languages (tag country) don't have /modules/paypal prepended.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
