### ISSUE TITLE
PayPaypal logos download is blocked by Paypal server (403) and this causes a big slowdown on each request

### ISSUE THREAD

**Issue by petzo** [PrestaShop/paypal#53]
When the [`updatePictures()`](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/paypal_logos.php#L127) method is called and it tries to update the logos, it can't succeed [here](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/paypal_logos.php#L135), because Paypal logo locations can't be opened via PHP. Paypal servers seem to be blocking the request with 403 error. Due to that reason this method is called on each request and is slowing the shop a lot (about 6 sec in my case).

This is happening for example at the "shoppingCartExtra" hook. What happens there:
- [`PaypalLogos::getLogos()`](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/paypal.php#L800) is called.
- [`PaypalLogos::getLocalLogo()`](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/paypal_logos.php#L62) is called
- [`PaypalLogos::updatePictures()`](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/paypal_logos.php#L104) is called

That is slow and is done on each hook call, and not [as designed - each week](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/paypal_logos.php#L132).
My temporary solution was to change the modified dates on the logos to a date in the future.

I can't think of a good longtime solution so that is why I'm reporting this here as an issue.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
