### ISSUE TITLE
Delayed Site Response

### ISSUE THREAD

**Issue by mrtwister76** [PrestaShop/paypal#58]
Hi,

The instantiation of a TLSVerificator object in the PayPal constructor causes a TLS check to be run against https://www.howsmyssl.com/a/check.

Unfortunately, the constructor is run on every page view, both front and backend, thus this causes lots of page delays :(
Especially at the moment when howsmyssl.com is taking between 5 - 35 seconds to respond to requests!

This check need to be removed from PayPal::__construct as a matter of urgency.

**To test, please comment out** the following line from the bottom of PayPal:: __construct:

**$tls_verificator = new TLSVerificator(true, $this);**

**Comment by mrtwister76** [comment]
I'm using version 3.11 official.
Looking at the master code here on github, the TLSVerificator line isn't present in the PayPal constructor!

**Comment by mrtwister76** [comment]
It would seem that the latest version here on github is 3.10.10.

Any idea of where to report this issue to the PayPal module development team?

**Comment by thoma202** [comment]
Hi thanks for the report, 
We are fixing the issue right now and will publish the upgrade in the coming hours. 

Thoma

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
