### ISSUE TITLE
Remove cart_quantity_delete 

### ISSUE THREAD

**Issue by Jufik** [PrestaShop/paypal#59]
[Javascript](https://github.com/PrestaShop/paypal/blob/b32f636963a636690a8d7e14910bb07e6fdb4ba5/views/js/paypal.js#L140) deletes things I'd like to keep in my OPC cart.

On which purpose is that button delete?

**Comment by HartLarsson** [comment]
yes seems strange it hides completely the voucher area too!

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) or create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
