### ISSUE TITLE
Development version

### ISSUE THREAD

**Issue by mcdado** [PrestaShop/paypal#60]
Where is the released version? Is it @thoma202's fork that is the new blessed release? Is it the one that we should use to make Pull Requests? This confusion, especially with fundamental modules like PayPal is not welcome. Shouldn't at least be on a `develop` branch in the `PrestaShop` organisation's repo?

**Comment by tickez** [comment]
I couldn't agree more. Very confusing and essentially makes contribution impossible...

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) or create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
