### ISSUE TITLE
Order Confirmation and id_order = 0

### ISSUE THREAD

**Issue by manfield** [PrestaShop/paypal#63]
Prestashop 1.6.1.9
Paypal Module: 3.11.1

I noticed that even if the id_order, processed by paypal payment is 0, the order is created correctly on backend, because code manages to find id_order, based on id_cart.

Though, the confirmation url call, is called passing id_order = 0:

`/module/paypal/submit?id_cart=19&id_module=87&id_order=0&key=4a6617b44f87913235a764d3bb6b743`

The result of this is the confirmation page does not show order details:

http://screencast.com/t/3fUMPL8MlcR

I found a workaround, as I posted here :https://www.prestashop.com/forums/topic/565752-paypal-integral-evolution-return-url-with-id-order0-no-order-in-bo/?p=2447951, but I leave you think about the right solution.

Cheers.

**Comment by presta260** [comment]
Hi Manfield,

I have exactly the same crazy problem. Did you activate IPN ( Instant Payment Notification) on your Paypal Account ? and Did you also configure your Paypal account with an URL return such as : "https://www.yourwebsite.com/modules/paypal/ipn.php" ?
Because I have tried your workaround by replacing the line 45 of the file "/modules/paypal/controllers/front/submit.php" but doesnot work on my Prestashop :(
I am using Paypal version 3.10 and Prestashop version 1.5.3.1

It seems that the problem appears only with the Paypal Integral Evolution.

Thank you very much for your consideration of helping and sharing.

Sincerely,

Cyril

**Comment by manfield** [comment]
Actually you don't need to configure IPN url, because prestashop passes to paypal automatically, so it's not necessary. In my configuration I did not trick with this parameter in Paypal panel.

First of all be absolutely sure your smarty and classes cache was completely emptied because it's a common issue.

Then, please check if in PS 1.5 (your version) in classes/order/Order.php the method getOrderByCartId($id_cart) exists (because I'm using PS 1.6.x).

And finally I attach my modified module version for you to try.
[paypal.zip](https://github.com/PrestaShop/paypal/files/666634/paypal.zip)

**Comment by presta260** [comment]
Hello Manfredi,

Thank you for your quick answer, I very appreciate it.

I have emptied all the cache in the folder:
cache/smarty/cache
cache/smarty/compile

and even in my browser.

I have checked what you asked and I do have the method
getOrderByCartId($id_cart) in my version 1.5.3.1 of Prestashop.

I have installed your module and it does not work :( .I am using Paypal
Integral evolution and I am thinking there is a file called : submit.php
also in the folder paypal\integral_evolution. Maybe there is also a
modification to do in this file, does not it ?

If you have some freetime, I can send you my BackOffice information it
would be faster for you to localise the problem.


Thank you again :)

Sincerely,

Cyril







2016-12-21 15:56 GMT+01:00 Manfredi Petruso <notifications@github.com>:

**Comment by manfield** [comment]
Yeah, but contact me via email: manfredi[at]fabvla.com
Moreover: be sure to configure paypal in sandbox mode before me trying some tests.
Thanks

**Comment by changuelsami** [comment]
@presta260 Hi, have you found a solution ? I'm having same troubles with PS 1.5 and Paypal 3.11.4, this is the return URL from Paypal : 
http://mysite.com/en/module/paypal/submit?id_cart=36548&id_module=134&**id_order=0**&key=1e0577e6b3de92684f5d69309

**Comment by 202-ecommerce** [comment]
Hi,

Can you open a ticket on our support website ?
https://support.202-ecommerce.com/en/support/home

Regards,
202 ecommerce

**Comment by manfield** [comment]
By the way the problem seems to be a different one.
The route to the front controller does not work. I suggest you to uninstall and re-install the paypal module.
Cheers.

**Comment by ahharu** [comment]
Any updates?

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
