### ISSUE TITLE
PayPal Order gives 500 Error - Payment received, no order created

### ISSUE THREAD

**Issue by M03G** [PrestaShop/paypal#66]
Hello
The problem described here - http://forge.prestashop.com/browse/PNM-3843
The comments I have described the reason (I think):
_I added logging and found that the record of database does not occur because the data set in parameter "secure_key" no value. And this column could not be empty in the database. Therefore, an error occurs._
**Column 'secure_key' cannot be null**

UPD: A value of "secure_key" empty because the module was not able to identify the customer id. And transmits the order entry id_customer = 0. It is logical that this user has no secure_key.

**Comment by M03G** [comment]
The array, which came to write the order in the method add() class ObjectModel.
    [id_address_delivery] => 0
    [id_address_invoice] => 0
    [id_cart] => 26989
    [id_currency] => 2
    [id_shop_group] => 1
    [id_shop] => 3
    [id_lang] => 1
    **[id_customer] => 0**
    [id_carrier] => 126
    [current_state] => 0
    **[secure_key] =>** 
    [payment] => PayPal
    [module] => paypal
    [recyclable] => 0
    [gift] => 0
    [gift_message] => 
    [mobile_theme] => 0
    [total_discounts] => 0
    [total_discounts_tax_incl] => 0
    [total_discounts_tax_excl] => 0
    [total_paid] => 40.38
    [total_paid_tax_incl] => 40.38
    [total_paid_tax_excl] => 40.38
    [total_paid_real] => 0
    [total_products] => 32.97
    [total_products_wt] => 32.97
    [total_shipping] => 7.41
    [total_shipping_tax_incl] => 7.41
    [total_shipping_tax_excl] => 7.41
    [carrier_tax_rate] => 0
    [total_wrapping] => 0
    [total_wrapping_tax_incl] => 0
    [total_wrapping_tax_excl] => 0
    [round_mode] => 2
    [round_type] => 2
    [shipping_number] => 
    [conversion_rate] => 1
    [invoice_number] => 0
    [delivery_number] => 0
    [invoice_date] => 0000-00-00 00:00:00
    [delivery_date] => 0000-00-00 00:00:00
    [valid] => 0
    [reference] => LCNSRJYED
    [date_add] => 2016-12-21 22:28:04
    [date_upd] => 2016-12-21 22:28:04

I think there (/modules/paypal/express_checkout/payment.php) is something going wrong:
369: $cart = $ppec->context->cart;
370: $customer = new Customer((int) $cart->id_customer);

**Comment by M03G** [comment]
If you pay "Express" line 48 $request_type = Tools::getValue('express_checkout'); return null...

**Comment by Dan-Orchard** [comment]
When is this being looked at please? This is a huge bug...

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
