### ISSUE TITLE
Paypal currency conversion not working - MAJOR issue!

### ISSUE THREAD

**Issue by petzo** [PrestaShop/paypal#7]
I've created an issue here: http://forge.prestashop.com/browse/PSCSX-5398

I'm copy/pasting here too:
Reproducible on a clean 1.6.0.14 installation.
Prices not converted in Paypal payment when Paypal currency is different from the user/shop currency.
The screenshots explain it very well, but steps to reproduce:
admin:
1. Clean Prestashop install
2. Install Paypal module
3. Install USD currency
4. Set Paypal currency to be shop default (EUR)
as user:
1. Select USD as currency
2. Buy something
3. Pay with Paypal
result:
1. Something that was $27.88 (USD) in the shop becomes €27.88 (EUR) in Paypal!!!
2. Shipping is not affected so $7.51 (USD) becomes €7.00 (EURO)
I can't stress this enough but this is MAJOR MAJOR issue!
![cart-summary](https://cloud.githubusercontent.com/assets/5909638/7283031/5e7b4d9a-e93c-11e4-95fb-4a26e62f8cee.png)
![default](https://cloud.githubusercontent.com/assets/5909638/7283033/5e9fea88-e93c-11e4-95c2-94bc974f5e5c.png)
![paypal-currency](https://cloud.githubusercontent.com/assets/5909638/7283034/5ea04d5c-e93c-11e4-85a1-91639a72587b.png)
![paypal](https://cloud.githubusercontent.com/assets/5909638/7283035/5ea0eb68-e93c-11e4-9893-1d576d4707ff.png)

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
