### ISSUE TITLE
Error shown to users on all correctly paid orders

### ISSUE THREAD

**Issue by intervia** [PrestaShop/paypal#81]
Prestashop v1.6.1.0 spanish
PayPal module  v3.11.5

On every order, an error like this one is shown to user in frontend when returning from PayPal:

> Please try to contact merchant:
> 1. An error occurred while processing payment.
> Total of the transaction (taxes incl): 54,41€
> Your order ID is: 575

Message is displayed in english, in a red background box below "Error en el pago" text, so it is not loading language files for some reason.

I have fixed it removing the conditional in express_checkout/submit.php

I've changed from this:
`if (!$order || !$order_state || (isset($order_state_message) && ($order_state_message == 'payment_error'))) {`

To this:
`if (!$order || !$order_state) {`

But It doesn't fix the problem, only remove the error message.
I suspect it may be related to the language file, but I can't find where the problem really is.

Can someone tell me why $order_state_message contains "payment_error" in correctly paid orders?

**Comment by sgodard202** [comment]
Hello,

$order_state_message contain the template mail send. I can't help you without other information.
Can you create ticket on https://addons.prestashop.com/en/contact-us?id_product=1748 ?
We need Ftp Connection and BO login.

Best regards

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
