### ISSUE TITLE
 Non-static method PaypalPlusPui::getByIdOrder() should not be called statically

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/paypal#85]
- Last PayPal module version: 3.11.6
- Last 1.6 PrestaShop version: 1.6.1.23
- PHP: 5.6.30
- HTTP server: Apache2

On final payment page, into PayPal popup window, I have this error: "Le système ne fonctionne pas pour le moment."

And from back log:

> [Wed Dec 19 17:40:09.130271 2018] [:error] [pid 21061] [client 192.168.100.100:57609] PHP Deprecated:  Non-static method PaypalPlusPui::getByIdOrder() should not be called statically, assuming $this from incompatible context in /var/www/html/modules/paypal/paypal.php on line 2625

**Comment by tvorgul** [comment]
Hello @Klemart3D !

Thank you for your comment. We have fixed this issue in the new version of the module (v.3.12.0 for PrestaShop 1.5-1.6): https://github.com/202-ecommerce/paypal/tree/release/3.12.0

Have a nice day !

**Comment by matks** [comment]
@tvorgul hello ! so it seems that https://github.com/202-ecommerce/paypal is a fork of https://github.com/PrestaShop/paypal/ and is the "main" repository

Is it temporary ? If not, maybe we could modify the README.md / CONTRIBUTING.md of this repository to redirect users to the right repository ?

**Comment by tvorgul** [comment]
Hello ! 

We will create a pull request for adding new changes to the PrestaShop project soon.

Thank you ! :)

**Comment by Klemart3D** [comment]
Hi, with PayPal module v3.12 error seems go out. You can close this ticket ;) Thank you.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
