### ISSUE TITLE
how to override the file paypal\paypal_orders.php?

### ISSUE THREAD

**Issue by jorbope** [PrestaShop/paypal#86]
I'm trying to override the class PayPalOrder (paypal\paypal_orders.php), I copied the entire file to 
<myshop>\override\modules\paypal\paypal_orders.php

I renamed the class in this way:

class PayPalOrderOverride extends PayPalOrder { .... }

and I modified the content of the function 
public static function getTransactionDetails($ppec = false, $payment_status = false);

because I got an error: PHP Notice:  Undefined index: PAYMENTREQUEST_0_SHIPPINGAMT
when I try to confirm a payment using Paypal.
Alter that I removed all cache directory content but it doesn't work.

what should I do to override this class?

**Comment by tvorgul** [comment]
Hello !

Thank you for your message.
We will be glad to help you. Could you please contact our support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) please? 

Thank you in advanced !

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
