### ISSUE TITLE
An error is displayed "Uncaught URIError: URI malformed" when we use a non supported currency

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/paypal#90]
Hi,

I tried to use PrestaShop v1.7.5.0 / PS1.7.4.4 & the PayPal module v4.4.2.
In the FO, we used a non-supported currency "Indian Rupee", when we try to complete an order with PayPal, an error in the console is displayed.
![image](https://user-images.githubusercontent.com/16067358/51846833-abcd6f80-231a-11e9-9223-c409b97aa4ac.png)

Thanks!

**Comment by tvorgul** [comment]
Hello,

Thank you for your message.
Could you please contact our support team via [module page on PrestaShop Addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748)?

Thank you in advanced !


Best regards,
202 ecommerce

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please check [PayPal User documentation](https://addons.prestashop.com/documentation/e582dd0854d8994e815d6c0e8886e703bfdf7713) or contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748). You can also create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
