### ISSUE TITLE
Prestashop 1.7 - Currency Conversion not working for gift wrapping cost in PayPal module

### ISSUE THREAD

**Issue by laxmariappan** [PrestaShop/paypal#91]
PayPal express checkout and pay with credit card methods have a strange issue with gift wrapping costs

The store has 4 currencies, all the values in the cart are getting converted correctly except the gift wrapping price.

Did anyone encounter this issue?

PayPal didn't set the "covertPrice" method's parameter convert to true.

```
public function formatPrice($price)
{
    $context = Context::getContext();
    $context_currency = $context->currency;
    $paypal = Module::getInstanceByName('paypal');
    if ($paypal->needConvert()) {
        $price = Tools::convertPrice($price, $context_currency, false);
    }﻿
    $price = number_format($price, Paypal::getDecimal(), ".", '');
    return﻿ $price;
}﻿
```

If I change it to true, that converts the currency value to selected currency, I get error code 0 the last step of checkout.

**Comment by tvorgul** [comment]
This module is maintained by 202 ecommerce. Since 2016, development has moved to another [repository](https://github.com/202-ecommerce/paypal).
To avoid confusions, this repository will be archived, while open issues and Pull Requests will be closed. 
For any questions, please contact 202 technical support team via [prestashop addons](https://addons.prestashop.com/fr/contactez-nous?id_product=1748) or create new issues via [202-ecommerce/paypal repository](https://github.com/202-ecommerce/paypal).
